/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "paperserver.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

add_out *
add_proc_1(paper *argp, CLIENT *clnt)
{
	static add_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD_PROC,
		(xdrproc_t) xdr_paper, (caddr_t) argp,
		(xdrproc_t) xdr_add_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
remove_proc_1(remove_in *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REMOVE_PROC,
		(xdrproc_t) xdr_remove_in, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

list_out *
list_proc_1(void *argp, CLIENT *clnt)
{
	static list_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LIST_PROC,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_list_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

info_out *
info_proc_1(info_in *argp, CLIENT *clnt)
{
	static info_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INFO_PROC,
		(xdrproc_t) xdr_info_in, (caddr_t) argp,
		(xdrproc_t) xdr_info_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

paper_out *
fetch_proc_1(fetch_in *argp, CLIENT *clnt)
{
	static paper_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FETCH_PROC,
		(xdrproc_t) xdr_fetch_in, (caddr_t) argp,
		(xdrproc_t) xdr_paper_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
