/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PAPERSERVER_H_RPCGEN
#define _PAPERSERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct paper {
	char *author_name;
	char *paper_name;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct paper paper;

struct info_out {
	char *author_name;
	char *paper_name;
};
typedef struct info_out info_out;

struct paper_out {
	int succes;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct paper_out paper_out;

struct list_out {
	int id;
	char *author_name;
	char *paper_title;
	struct list_out *next;
};
typedef struct list_out list_out;

typedef int add_out;

typedef int remove_in;

typedef int info_in;

typedef int fetch_in;

#define PAPERSERVER_PROG 0x20001234
#define PAPERSERVER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD_PROC 1
extern  add_out * add_proc_1(paper *, CLIENT *);
extern  add_out * add_proc_1_svc(paper *, struct svc_req *);
#define REMOVE_PROC 2
extern  bool_t * remove_proc_1(remove_in *, CLIENT *);
extern  bool_t * remove_proc_1_svc(remove_in *, struct svc_req *);
#define LIST_PROC 3
extern  list_out * list_proc_1(void *, CLIENT *);
extern  list_out * list_proc_1_svc(void *, struct svc_req *);
#define INFO_PROC 4
extern  info_out * info_proc_1(info_in *, CLIENT *);
extern  info_out * info_proc_1_svc(info_in *, struct svc_req *);
#define FETCH_PROC 5
extern  paper_out * fetch_proc_1(fetch_in *, CLIENT *);
extern  paper_out * fetch_proc_1_svc(fetch_in *, struct svc_req *);
extern int paperserver_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD_PROC 1
extern  add_out * add_proc_1();
extern  add_out * add_proc_1_svc();
#define REMOVE_PROC 2
extern  bool_t * remove_proc_1();
extern  bool_t * remove_proc_1_svc();
#define LIST_PROC 3
extern  list_out * list_proc_1();
extern  list_out * list_proc_1_svc();
#define INFO_PROC 4
extern  info_out * info_proc_1();
extern  info_out * info_proc_1_svc();
#define FETCH_PROC 5
extern  paper_out * fetch_proc_1();
extern  paper_out * fetch_proc_1_svc();
extern int paperserver_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paper (XDR *, paper*);
extern  bool_t xdr_info_out (XDR *, info_out*);
extern  bool_t xdr_paper_out (XDR *, paper_out*);
extern  bool_t xdr_list_out (XDR *, list_out*);
extern  bool_t xdr_add_out (XDR *, add_out*);
extern  bool_t xdr_remove_in (XDR *, remove_in*);
extern  bool_t xdr_info_in (XDR *, info_in*);
extern  bool_t xdr_fetch_in (XDR *, fetch_in*);

#else /* K&R C */
extern bool_t xdr_paper ();
extern bool_t xdr_info_out ();
extern bool_t xdr_paper_out ();
extern bool_t xdr_list_out ();
extern bool_t xdr_add_out ();
extern bool_t xdr_remove_in ();
extern bool_t xdr_info_in ();
extern bool_t xdr_fetch_in ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PAPERSERVER_H_RPCGEN */
